- name: understand facts
  hosts: centos:ubuntu # or all
  become: yes
  tasks:
  - name: print all facts
    debug:
      msg: "All facts: {{ansible_facts}}"
  #just imagine we don't have user  module in ansible
  - name: add user ubuntu
    ansible.builtin.command: adduser devi
    when: ansible_facts['distribution'] == "Ubuntu"

  - name: add user centos
    ansible.builtin.command: useradd devi
    when: ansible_facts['distribution'] == "CentOs"